sudo: required 
services:
  - docker 

before_install:
  - docker build -t lukeboerdam/docker-react-test -f DockerFile.dev .

script: 
  - docker run lukeboerdam/docker-react-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "Test-React"
  env: "TestReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-407753684447"
  bucket_path: "Test-React"
  on: 
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"

  


    